import { Inter } from "next/font/google";
import "../globals.css";
import Footer from "@/Component/Footer/Footer";
import Header from "@/Component/Header/Header";
import FirstHeader from "@/Component/Header/FirstHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Zas-71",
  description: "Generated by create next app",
};

export default function WithLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex mt-5">
          <div className="mr-[100px] ml-4">
            <FirstHeader></FirstHeader>
          </div>
          <div>
            <Header></Header>
            {children}
          </div>
        </div>
        <Footer></Footer>
      </body>
    </html>
  );
}
