import { Inter } from "next/font/google";
import "../globals.css";
import ProfileHeader from "@/Component/ProfileHeader/ProfileHeader";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Zas-71",
  description: "Generated by create next app",
};

export default function ProfileLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <div>
            <ProfileHeader></ProfileHeader>
          </div>
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
