import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/Component/Header/Navbar'
import Footer from '@/Component/Footer/Footer'
import Header from '@/Component/Header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Zas-71',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </body>
    </html>
  )
}
